name: softfarm
description: Soft Farm.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  google_fonts: ^4.0.4
  equatable: ^2.0.5
  parse_server_sdk_flutter: ^6.0.0
  shared_preferences: ^2.2.1
  mask_text_input_formatter: ^2.5.0
  flutter_modular: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

